// KefinTweaks Configuration
// This file is automatically generated by KefinTweaks Configuration UI
// Do not edit manually unless you know what you're doing

window.KefinTweaksConfig = {
  "kefinTweaksRoot": "https://cdn.jsdelivr.net/gh/ranaldsgift/KefinTweaks@latest/",
  "scripts": {
    "watchlist": true,
    "homeScreen": true,
    "search": true,
    "infiniteScroll": false,
    "removeContinue": true,
    "skinManager": false,
    "headerTabs": true,
    "customMenuLinks": true,
    "breadcrumbs": false,
    "playlist": false,
    "itemDetailsCollections": false,
    "flattenSingleSeasonShows": true,
    "seriesInfo": true,
    "collections": false,
    "subtitleSearch": true,
    "exclusiveElsewhere": true,
    "backdropLeakFix": true,
    "dashboardButtonFix": true
  },
  "homeScreen": {
    "defaultItemLimit": 16,
    "defaultSortOrder": "Random",
    "defaultCardFormat": "Poster",
    "recentlyReleased": {
      "enabled": true,
      "movies": {
        "enabled": true,
        "itemLimit": 10,
        "name": "New Movies",
        "sortOrder": "Random",
        "sortOrderDirection": "Descending",
        "cardFormat": "Poster",
        "order": 7,
        "isPlayed": null,
        "minAgeInDays": 0,
        "maxAgeInDays": 120
      },
      "episodes": {
        "enabled": true,
        "itemLimit": 7,
        "name": "New Episodes",
        "sortOrder": "PremiereDate",
        "sortOrderDirection": "Descending",
        "cardFormat": "Thumb",
        "order": 6,
        "isPlayed": null,
        "minAgeInDays": 0,
        "maxAgeInDays": 1
      }
    },
    "recentlyAddedInLibrary": {
      "5ddaa59a73205234890fdcfc683e14ed": {
        "enabled": true,
        "itemLimit": 7,
        "name": "Added Series",
        "cardFormat": "Thumb",
        "order": 3
      },
      "47a99f022e445cb2d5d18d1a456b0c23": {
        "enabled": true,
        "itemLimit": 7,
        "name": "Added Movies",
        "cardFormat": "Poster",
        "order": 4
      }
    },
    "trending": {
      "enabled": false,
      "itemLimit": 16,
      "name": "Trending",
      "sortOrder": "Random",
      "sortOrderDirection": "Ascending",
      "cardFormat": "Poster",
      "order": 32,
      "isPlayed": null
    },
    "popularTVNetworks": {
      "enabled": false,
      "minimumShowsForNetwork": 5,
      "itemLimit": 16,
      "name": "Popular TV Networks",
      "sortOrder": "Random",
      "sortOrderDirection": "Ascending",
      "cardFormat": "Poster",
      "order": 61
    },
    "watchlist": {
      "enabled": true,
      "itemLimit": 15,
      "name": "Watchlist",
      "sortOrder": "Name",
      "sortOrderDirection": "Ascending",
      "cardFormat": "Poster",
      "order": 2
    },
    "watchAgain": {
      "enabled": true,
      "itemLimit": 100,
      "name": "Watch Movie Again",
      "sortOrder": "SortName",
      "sortOrderDirection": "Ascending",
      "cardFormat": "Poster",
      "order": 14
    },
    "upcoming": {
      "enabled": false,
      "itemLimit": 10,
      "name": "Upcoming Episodes",
      "cardFormat": "Thumb",
      "order": 8
    },
    "imdbTop250": {
      "enabled": true,
      "itemLimit": 16,
      "name": "Top Rated",
      "sortOrder": "SortName",
      "sortOrderDirection": "Ascending",
      "cardFormat": "Poster",
      "order": 10,
      "isPlayed": false
    },
    "seasonal": {
      "enabled": false,
      "enableSeasonalAnimations": true,
      "enableSeasonalBackground": true,
      "defaultItemLimit": 16,
      "defaultSortOrder": "Random",
      "defaultCardFormat": "Poster",
      "seasons": [
        {
          "id": "halloween",
          "name": "Halloween",
          "enabled": true,
          "startDate": "10-01",
          "endDate": "10-31",
          "order": 100,
          "sections": [
            {
              "id": "halloween-tag",
              "enabled": true,
              "name": "Halloween Movies",
              "type": "Tag",
              "source": "halloween",
              "itemLimit": 16,
              "sortOrder": "Random",
              "sortOrderDirection": "Ascending",
              "cardFormat": "Poster",
              "order": 50,
              "renderMode": "Normal",
              "spotlight": false,
              "discoveryEnabled": false,
              "searchTerm": "",
              "includeItemTypes": [
                "Movie"
              ],
              "additionalQueryOptions": []
            },
            {
              "id": "halloween-horror",
              "enabled": true,
              "name": "Horror Genre",
              "type": "Genre",
              "source": "Horror",
              "itemLimit": 16,
              "sortOrder": "Random",
              "sortOrderDirection": "Ascending",
              "cardFormat": "Poster",
              "order": 51
            },
            {
              "id": "halloween-thriller",
              "enabled": true,
              "name": "Thriller Genre",
              "type": "Genre",
              "source": "Thriller",
              "itemLimit": 16,
              "sortOrder": "Random",
              "sortOrderDirection": "Ascending",
              "cardFormat": "Poster",
              "order": 52
            },
            {
              "id": "seasonal-0-section-3",
              "enabled": true,
              "name": "New Section",
              "type": "Genre",
              "source": "",
              "itemLimit": 16,
              "sortOrder": "Random",
              "sortOrderDirection": "Ascending",
              "cardFormat": "Poster",
              "order": 100,
              "renderMode": "Normal",
              "spotlight": false,
              "discoveryEnabled": false,
              "searchTerm": "",
              "includeItemTypes": [
                "Movie"
              ],
              "additionalQueryOptions": []
            }
          ]
        },
        {
          "id": "thanksgiving",
          "name": "Thanksgiving",
          "enabled": true,
          "startDate": "11-20",
          "endDate": "11-30",
          "order": 50,
          "sections": [
            {
              "id": "seasonal-2-section-0",
              "enabled": true,
              "name": "Thanksgiving Movies",
              "type": "Tag",
              "source": "thanksgiving",
              "itemLimit": 16,
              "sortOrder": "Random",
              "sortOrderDirection": "Ascending",
              "cardFormat": "Poster",
              "order": 50,
              "renderMode": "Spotlight",
              "spotlight": true,
              "discoveryEnabled": false,
              "searchTerm": "",
              "includeItemTypes": [
                "Movie"
              ],
              "additionalQueryOptions": []
            },
            {
              "id": "seasonal-2-section-1",
              "enabled": true,
              "name": "Thanksgiving Episodes",
              "type": "Parent",
              "source": "",
              "itemLimit": 16,
              "sortOrder": "Random",
              "sortOrderDirection": "Ascending",
              "cardFormat": "Thumb",
              "order": 51,
              "renderMode": "Normal",
              "spotlight": false,
              "discoveryEnabled": false,
              "searchTerm": "thanksgiving",
              "includeItemTypes": [
                "Episode"
              ],
              "additionalQueryOptions": []
            }
          ]
        },
        {
          "id": "christmas",
          "name": "Christmas",
          "enabled": true,
          "startDate": "12-01",
          "endDate": "12-31",
          "order": 100,
          "sections": [
            {
              "id": "seasonal-1-section-0",
              "enabled": true,
              "name": "Christmas Movies",
              "type": "Tag",
              "source": "christmas",
              "itemLimit": 16,
              "sortOrder": "Random",
              "sortOrderDirection": "Ascending",
              "cardFormat": "Poster",
              "order": 50,
              "renderMode": "Spotlight",
              "spotlight": true,
              "discoveryEnabled": false,
              "searchTerm": "",
              "includeItemTypes": [
                "Movie"
              ],
              "additionalQueryOptions": []
            },
            {
              "id": "seasonal-1-section-1",
              "enabled": true,
              "name": "Christmas Episodes",
              "type": "Parent",
              "source": "",
              "itemLimit": 16,
              "sortOrder": "Random",
              "sortOrderDirection": "Ascending",
              "cardFormat": "Thumb",
              "order": 51,
              "renderMode": "Normal",
              "spotlight": false,
              "discoveryEnabled": false,
              "searchTerm": "christmas",
              "includeItemTypes": [
                "Episode"
              ],
              "additionalQueryOptions": []
            }
          ]
        }
      ]
    },
    "discovery": {
      "enabled": true,
      "infiniteScroll": false,
      "randomizeOrder": false,
      "minPeopleAppearances": 10,
      "minGenreMovieCount": 50,
      "spotlightDiscoveryChance": 1,
      "renderSpotlightAboveMatching": true,
      "defaultItemLimit": 16,
      "defaultSortOrder": "Random",
      "defaultCardFormat": "Poster",
      "sectionTypes": {
        "spotlightGenre": {
          "itemLimit": 15,
          "name": "Good Movies",
          "cardFormat": "Poster",
          "order": 99,
          "isPlayed": null,
          "enabled": true
        },
        "spotlightNetwork": {
          "itemLimit": 15,
          "name": "Good Series",
          "cardFormat": "Thumb",
          "order": 100,
          "isPlayed": null,
          "enabled": true
        },
        "genreMovies": {
          "itemLimit": 10,
          "name": "[Genre]",
          "cardFormat": "Poster",
          "order": 200,
          "isPlayed": null,
          "enabled": true
        },
        "studioShows": {
          "itemLimit": 10,
          "name": "[Studio]",
          "cardFormat": "Thumb",
          "order": 201,
          "isPlayed": null,
          "enabled": true
        },
        "collections": {
          "itemLimit": 20,
          "name": "Diddys",
          "cardFormat": "Poster",
          "order": 98,
          "isPlayed": null,
          "enabled": false,
          "minimumItems": 10
        },
        "becauseYouWatched": {
          "itemLimit": 10,
          "name": "Because of Diddy",
          "cardFormat": "Poster",
          "order": 102,
          "isPlayed": null,
          "enabled": true
        },
        "becauseYouLiked": {
          "itemLimit": 10,
          "name": "Because you liked [Movie]",
          "cardFormat": "Poster",
          "order": 103,
          "isPlayed": null,
          "enabled": false
        },
        "starringTopActor": {
          "itemLimit": 10,
          "name": "Starring [Actor]",
          "cardFormat": "Poster",
          "order": 100,
          "isPlayed": null,
          "enabled": false
        },
        "directedByTopDirector": {
          "itemLimit": 16,
          "name": "Directed by [Director]",
          "cardFormat": "Poster",
          "order": 100,
          "isPlayed": null,
          "enabled": false
        },
        "writtenByTopWriter": {
          "itemLimit": 16,
          "name": "Written by [Writer]",
          "cardFormat": "Poster",
          "order": 100,
          "isPlayed": null,
          "enabled": false
        },
        "becauseYouRecentlyWatched": {
          "itemLimit": 10,
          "name": "Because you watched [Movie]",
          "cardFormat": "Poster",
          "order": 104,
          "isPlayed": null,
          "enabled": false
        },
        "starringActorRecentlyWatched": {
          "itemLimit": 16,
          "name": "Starring [Actor] because you recently watched [Movie]",
          "cardFormat": "Poster",
          "order": 100,
          "isPlayed": null,
          "enabled": false
        },
        "directedByDirectorRecentlyWatched": {
          "itemLimit": 16,
          "name": "Directed by [Director] because you recently watched [Movie]",
          "cardFormat": "Poster",
          "order": 100,
          "isPlayed": null,
          "enabled": false
        },
        "writtenByWriterRecentlyWatched": {
          "itemLimit": 16,
          "name": "Written by [Writer] because you recently watched [Movie]",
          "cardFormat": "Poster",
          "order": 100,
          "isPlayed": null,
          "enabled": false
        }
      }
    },
    "customSections": [
      {
        "id": "custom-section-0",
        "enabled": true,
        "name": "Watch Serie Again",
        "type": "Parent",
        "source": "",
        "itemLimit": 20,
        "sortOrder": "Name",
        "sortOrderDirection": "Descending",
        "cardFormat": "Thumb",
        "order": 13,
        "renderMode": "Normal",
        "spotlight": false,
        "discoveryEnabled": false,
        "searchTerm": "",
        "includeItemTypes": [
          "Series"
        ],
        "additionalQueryOptions": [
          {
            "key": "isPlayed",
            "value": true
          }
        ]
      }
    ]
  },
  "exclusiveElsewhere": {
    "hideServerName": false
  },
  "search": {
    "enableJellyseerr": true
  },
  "defaultSkin": "ElegantFin",
  "skins": [
    {
      "name": "ElegantFin",
      "enabled": false,
      "hidden": false
    },
    {
      "name": "NeutralFin",
      "enabled": false,
      "hidden": false
    },
    {
      "name": "GlassFin",
      "enabled": false,
      "hidden": false
    },
    {
      "name": "Jellypane",
      "enabled": false,
      "hidden": false
    },
    {
      "name": "Finimalism",
      "enabled": false,
      "hidden": false
    },
    {
      "name": "Jellyfish",
      "enabled": false,
      "hidden": false
    },
    {
      "name": "Glassmorphism",
      "enabled": false,
      "hidden": false
    },
    {
      "name": "Jamfin",
      "enabled": false,
      "hidden": false
    },
    {
      "name": "Scyfin",
      "enabled": false,
      "hidden": false
    },
    {
      "name": "Catppuccin",
      "enabled": false,
      "hidden": false
    },
    {
      "name": "Flow",
      "enabled": false,
      "hidden": false
    },
    {
      "name": "Ultrachromic",
      "enabled": false,
      "hidden": false
    }
  ],
  "themes": [],
  "customMenuLinks": [],
  "enabled": true,
  "flattenSingleSeasonShows": {
    "hideSingleSeasonContainer": false
  },
  "optionalIncludes": [
    {
      "key": "global-lscambo13-custom-media-covers-latest-min.css",
      "enabled": false
    },
    {
      "key": "global-JamsRepos-central-libraries-small.css",
      "enabled": false
    },
    {
      "key": "global-JamsRepos-hide-my-media.css",
      "enabled": false
    },
    {
      "key": "global-JamsRepos-smaller-cast.css",
      "enabled": false
    },
    {
      "key": "global-LitCastVlog-ScyFlow-EpisodeGrid.css",
      "enabled": true
    },
    {
      "key": "global-LitCastVlog-ScyFLow-RoundCastCrew.css",
      "enabled": true
    },
    {
      "key": "global-CTalvio-smallercast.css",
      "enabled": true
    },
    {
      "key": "global-CTalvio-episodes_compactlist.css",
      "enabled": true
    },
    {
      "key": "global-CTalvio-episodes_grid.css",
      "enabled": true
    },
    {
      "key": "global-CTalvio-pan-animation.css",
      "enabled": true
    },
    {
      "key": "global-LitCastVlog-ScyFlow-AnimatedOverlay.css",
      "enabled": true
    }
  ]
};
